spring.application.name=self
spring.datasource.url=jdbc:mysql://localhost:3306/self
spring.datasource.username=qwertyuiopasdfghjklzxcvbnm
spring.datasource.password=qwertyujklsdfghjkxcvbnmpoiuytrew

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
