spring.application.name=self
spring.datasource.url=jdbc:mysql://localhost:3306/self
spring.datasource.username=root
spring.datasource.password=shreya

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true